### PR TITLE
I couldn't help myself

### PR DESCRIPTION
**Pull request by lukehefson**
[Rendered view of how it could look](https://github.com/lukehefson/useful-links/blob/11f6ff35a7b8b99b9d0a2359602753381c9b3007/README.md) if you merged this pull request.

### CODE REVIEW

**Comment by lukehefson** [comment]
yeah!

**Comment by jimiswells** [comment]
thats the first merge pull i've ever done
what a feeling

**Comment by jimiswells** [comment]
thanks

**Comment by jimiswells** [comment]
wizard

**Pull request merged**
